(define (fringe items)
  (define (fringe-iter items new)
    (cond ((null? items) new)
	  ((pair? items) ))))

(define x (list (list 1 2) (list 3 4)))
   (fringe x)
(1 2 3 4)
   (fringe (list x x))
(1 2 3 4 1 2 3 4)